ktor:
  application:
    modules:
      - ru.beeline.payment.ApplicationKt.module
  deployment:
    port: 8081
psql:
  user: "$POSTGRES_USER:user"
  password: "$POSTGRES_PASSWORD:password"
  schema: "$POSTGRES_SCHEMA:payment"
  url: "$POSTGRES_URL:jdbc:postgresql://postgresql-payment:5432/payment_db"