apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-app
spec:
  selector:
    app: payment-app
  ports:
    - port: 80
      name: http
      targetPort: web
  type: ClusterIP
