prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
grafana:
  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: nginx
    }
    hosts:
      - grafana.arch.homework
    path: /
