databaseChangeLog:
  - changeSet:
      id:  1
      author:  mppetrov
      changes:
        - sql:
            "CREATE SCHEMA IF NOT EXISTS warehouse;"
        - createTable:
            schemaName: warehouse
            tableName: warehouse
            columns:
              - column:
                  name: id
                  type: char(36)
                  constraints:
                    primaryKey: true
                    unique: true
                    nullable: false
              - column:
                  name: order_id
                  type: char(36)
              - column:
                  name: item
                  type: varchar(256)
              - column:
                  name: status
                  type: varchar(16)