apiVersion: batch/v1
kind: Job
metadata:
  name: migration-ddl-warehouse
spec:
  template:
    spec:
      containers:
        - name: liquibase
          image: liquibase/liquibase:latest
          command: ["liquibase", "--defaultsFile=/liquibase/properties/liquibase.properties", "update"]
          volumeMounts:
            - name: cm-changelog
              mountPath: "/liquibase/changelog/"
              readOnly: true
            - name: cm-properties
              mountPath: "/liquibase/properties/"
              readOnly: true
      restartPolicy: Never
      volumes:
      - name: cm-changelog
        configMap:
          name: config-migration-changelog-warehouse
      - name: cm-properties
        configMap:
          name: config-migration-properties-warehouse