apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-postgres
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: postgresql-billing
    database.port: 5432
    database.user: postgres
    database.password: billing
    database.dbname: billing_db
    topic.prefix: postgres
    table.include.list: billing.history_billings
    plugin.name: pgoutput
    topic.creation.enable: true
    topic.creation.default.replication.factor: 1
    topic.creation.default.partitions: 1
    topic.creation.default.cleanup.policy: compact
    topic.creation.default.compression.type: lz4
    decimal.handling.mode: double