apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
  labels:
    app: warehouse-app
spec:
  selector:
    app: warehouse-app
  ports:
    - port: 80
      name: http
      targetPort: web
  type: ClusterIP
