ktor:
  application:
    modules:
      - ru.beeline.warehouse.ApplicationKt.module
  deployment:
    port: 8082
psql:
  user: "$POSTGRES_USER:user"
  password: "$POSTGRES_PASSWORD:password"
  schema: "$POSTGRES_SCHEMA:schema_test"
  url: "$POSTGRES_URL:jdbc:postgresql://localhost:5432/db_test"