ktor:
  application:
    modules:
      - ru.beeline.notification.ApplicationKt.module
  deployment:
    port: 8086

psql:
  user: "$POSTGRES_USER:user"
  password: "$POSTGRES_PASSWORD:password"
  schema: "$POSTGRES_SCHEMA:notification"
  url: "$POSTGRES_URL:jdbc:postgresql://postgresql-notification:5432/notification_db"

kafka:
  bootstrap: "$KAFKA_BOOTSTRAP:debezium-cluster-kafka-bootstrap:9092"
  groupId: "$KAFKA_GROUP_ID:notification"
  topic: "$KAFKA_TOPIC:postgres.billing.history_billings"
  keyDeserializer: "$KAFKA_KEY_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer"
  valueDeserializer: "$KAFKA_VALUE_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer"
  offsetReset: "$KAFKA_OFFSET_RESET:latest"

svcs:
  - user:
      host: "$USER_HOST:user-service"
      port: "$USER_PORT:80"
      path: "$USER_PATH:user"