apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-app
spec:
  selector:
    app: notification-app
  ports:
    - port: 80
      name: http
      targetPort: web
  type: ClusterIP
