databaseChangeLog:
  - changeSet:
      id:  1
      author:  mppetrov
      changes:
        - sql:
            "CREATE SCHEMA IF NOT EXISTS users;"
        - createTable:
            schemaName: users
            tableName: users
            columns:
              - column:
                  name: id
                  type: char(36)
                  constraints:
                    primaryKey: true
                    unique: true
                    nullable: false
              - column:
                  name: billing_id
                  type: char(36)
              - column:
                  name: name
                  type: varchar(128)
              - column:
                  name: email
                  type: varchar(128)