{
 "title": "monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "API Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS GET /user/{id}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{route=\"/user/{id}\",method=\"GET\"}[1m]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{status=~\"5.*\",method=\"GET\",route=\"/user/{id}\"}[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "LETENCY GET /user/{id}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(ktor_http_server_requests_seconds_bucket{method=\"GET\",route=\"/user/{id}\"}[1m]))) * 1000",
     "legendFormat": "q=0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ktor_http_server_requests_seconds_bucket{method=\"GET\",route=\"/user/{id}\"}[1m]))) * 1000",
     "legendFormat": "q=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/api/a\"}[1m]))) * 1000",
     "legendFormat": "q=0.99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/api/a\"}[1m]))) * 1000",
     "legendFormat": "q=max"
    }
   ]
  },
  { "title": "k8s Metrics CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"otus-ms-hw-transactions\", pod=~\"user-deployment.*\"}[1m])) by(pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEMORY USAGE (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"otus-ms-hw-transactions\",pod=~\"user-deployment.+\"}[1m])) by(pod) / 1024 /1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}