ktor:
  application:
    modules:
      - ru.beeline.billing.ApplicationKt.module
  deployment:
    port: 8085
psql:
  user: "$POSTGRES_USER:user"
  password: "$POSTGRES_PASSWORD:password"
  schema: "$POSTGRES_SCHEMA:billing"
  url: "$POSTGRES_URL:jdbc:postgresql://postgresql-billing:5432/billing_db"