apiVersion: v1
kind: Service
metadata:
  name: billing-service
  labels:
    app: billing-app
spec:
  selector:
    app: billing-app
  ports:
    - port: 80
      name: http
      targetPort: web
  type: ClusterIP
