apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-service
  labels:
    app: fluent-bit-app
spec:
  selector:
    app: fluent-bit-app
  ports:
    - port: 2020
      name: service
      targetPort: service
    - port: 24224
      name: forward
      targetPort: forward
  type: ClusterIP
