databaseChangeLog:
  - changeSet:
      id:  1
      author:  mppetrov
      changes:
        - sql:
            "CREATE SCHEMA IF NOT EXISTS payment;"
        - createTable:
            schemaName: payment
            tableName: payments
            columns:
              - column:
                  name: id
                  type: char(36)
                  constraints:
                    primaryKey: true
                    unique: true
                    nullable: false
              - column:
                  name: order_id
                  type: char(36)
              - column:
                  name: cost
                  type: double
              - column:
                  name: status
                  type: varchar(16)