config:
  clientID: "otus-ms-service-user"
  clientSecret: "tlDTc1VyLLdXcsreWKSUUlmCg67gUcIh"
  configFile: |
    reverse_proxy = true
    code_challenge_method = "S256"
    provider = "keycloak-oidc"
    redirect_url = "http://oauth2.arch.homework/callback"
    oidc_issuer_url = "http://keycloak.otus-ms-hw-transactions/realms/otus-ms-svc-user"
    insecure_oidc_skip_issuer_verification = true
    email_domains = [ "*" ]
    cookie_secure = false
    silence_ping_logging = true
    set_authorization_header = true
    skip_jwt_bearer_tokens = true
sessionStorage:
  type: cookie
redis:
  enabled: false
ingress:
  enabled: true
  className: nginx
  path: /
  hosts:
    - oauth2.arch.homework