
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
#    nginx.ingress.kubernetes.io/auth-url: "http://keycloak.otus-ms-hw-transactions/oauth2/auth"
#    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization"

spec:
  rules:
  - http:
        paths:
          - path: /user(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 80
  ingressClassName: nginx