databaseChangeLog:
  - changeSet:
      id:  1
      author:  mppetrov
      changes:
        - sql:
            "CREATE SCHEMA IF NOT EXISTS notification;"
        - createTable:
            schemaName: notification
            tableName: notifications
            columns:
              - column:
                  name: id
                  type: char(36)
                  constraints:
                    primaryKey: true
                    unique: true
                    nullable: false
              - column:
                  name: user_id
                  type: char(36)
              - column:
                  name: message
                  type: varchar(256)
              - column:
                  name: email
                  type: varchar(128)