databaseChangeLog:
  - changeSet:
      id:  1
      author:  mppetrov
      changes:
        - sql:
            "CREATE SCHEMA IF NOT EXISTS orders;"
        - createTable:
            schemaName: orders
            tableName: orders
            columns:
              - column:
                  name: id
                  type: char(36)
                  constraints:
                    primaryKey: true
                    unique: true
                    nullable: false
              - column:
                  name: status
                  type: varchar(16)
        - createTable:
            schemaName: orders
            tableName: order_items
            columns:
              - column:
                  name: id
                  type: char(36)
                  constraints:
                    primaryKey: true
                    unique: true
                    nullable: false
              - column:
                  name: order_id
                  type: char(36)
              - column:
                  name: item
                  type: varchar(256)
              - column:
                  name: amount
                  type: integer
              - column:
                  name: price
                  type: double